name: Scheduled Script Run

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        # Get the complete Chrome version
        COMPLETE_CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //' | cut -d' ' -f1)

        # Get the major version of Chrome
        CHROME_MAJOR_VERSION=$(echo "$COMPLETE_CHROME_VERSION" | cut -d. -f1)

        # Get the corresponding ChromeDriver version
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")

        # Download and install ChromeDriver
        wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas requests

    - name: Run the script
      run: python traffic_incidents_map/scraper_3.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "evandapplegate@gmail.com"
        git config --global user.name "evanapplegate"
        git add traffic_incidents_map/incidents.csv
        git commit -m "Update incidents.csv" || exit 0
        git push
