name: Scheduled update of incidents.csv

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update_incidents:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: traffic_incidents_map
        
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install selenium pandas requests

    - name: Print Working Directory
      run: pwd
        
    - name: Run scraper_3.py
      run: |
        python scraper_3.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add traffic_incidents_map/incidents.csv
        git commit -m "Update incidents.csv [skip ci]" || true
        git push
