name: Scheduled update of incidents.csv

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update_incidents:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install selenium pandas requests

    - name: Change directory to traffic_incidents_map
      run: cd traffic_incidents_map

    - name: Print Working Directory
      run: pwd

    - name: Run scraper_3.py
      run: |
        python scraper_3.py
